<?php

namespace GM\UtilisateurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository
{
	public function getIdUtilisateur($username)
	{
		$query = $this->_em->createQuery('SELECT u.id FROM GMUtilisateurBundle:Utilisateur u WHERE u.username = :username');
		$query->setParameter('username', $username);
		$results = $query->getOneOrNullResult();
	
		return $results;
	}
}
