<?php

namespace GM\CarnetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CarnetListeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarnetListeRepository extends EntityRepository
{
	public function supprimerCarnetListe($nom)
	{
		$query = $this->_em->createQuery('DELETE FROM GMCarnetBundle:CarnetListe cl WHERE cl.nom = :nom');
		$query->setParameter('nom', $nom);
		$results = $query->getResult();
	
		return $results;
	}
	
	public function verificationCarnetListe($nom)
	{
		$query = $this->_em->createQuery('SELECT cl.nom FROM GMCarnetBundle:CarnetListe cl WHERE cl.nom = :nom');
		$query->setParameter('nom', $nom);
		$results = $query->getOneOrNullResult();
	
		return $results;
	}
}
