<?php

namespace GM\CarnetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ListeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeRepository extends EntityRepository
{
	public function getIdListe($name)
	{
		$query = $this->_em->createQuery('SELECT l.id FROM GMCarnetBundle:Liste l WHERE l.name= :name');
		$query->setParameter('name', $name);
		$results = $query->getOneOrNullResult();
	
		return $results;
	}
	
	public function verificationPresence($name)
	{
		$query = $this->_em->createQuery('SELECT l.name FROM GMCarnetBundle:Liste l WHERE l.name = :name');
		$query->setParameter('name', $name);
		$results = $query->getOneOrNullResult();
	
		return $results;
	}
}
